### ISSUE TITLE
Customization to disable the update timer

### ISSUE THREAD

**Issue by sorend** [bcardoso/notmuch-x#1]
Hi:

Thank you for a great addition to notmuch in emacs.

I am running "notmuch new" in a cronjob (sometimes I do not have Emacs open :see_no_evil:).

Because of that sometimes the notmuch-x-update fails, because my cronjob is running together with notmuch-x-update.

I can disable this behavior by setting `(setq notmuch-x--update-timer t)` in my configuration.

However, it would be more intuitive if there was a customization to enable/disable the internal "notmuch new".

Let me know what you think. Thanks.

BR,
Soren

**Comment by bcardoso** [comment]
Hi Soren, thanks for the feedback! I'm glad this package has been useful to you :)

Are you starting notmuch with `notmuch-x-run-notmuch`? If so, try setting `notmuch-x--auto-update` to nil. (see 5b3f16374ca063d96e4b77ae7cc31450540fc2af)

**Comment by sorend** [comment]
Works great, thanks for the quick update :-)
