### ISSUE TITLE
Notmuch-x-run-notmuch fails if display-time-mode is not set.

### ISSUE THREAD

**Issue by sorend** [bcardoso/notmuch-x#2]
Hi:

Thanks for a great addition to notmuch :-)

When I start `notmuch-x-run-notmuch` without `(display-time-mode 1)` in my configuration, notmuch-x-run-notmuch fails with:
`notmuch-x-mode-line-indicator: Symbol’s value as variable is void: display-time-mail-icon`

On the second start it works.

**Comment by bcardoso** [comment]
Hi Soren, thanks again for the feedback!

I wasn't aware of this. Let me know if db095d6ddf0d2bfdca6a907ca3245cfcaf36a1c6 solves it for you.

**Comment by sorend** [comment]
Also fixes the issue, thanks again for quick resolution :-) 

BR,
Søen
